### ISSUE TITLE
Does not honour line breaks in rows

### ISSUE THREAD

**Issue by timwraight** [nvie/vim-rst-tables#6]
reST supports directives within tables, but these often require line breaks within rows. vim-rst-tables currently joins all lines into one when reflowing tables. Would it be possible to modify the plugin so that line breaks can be honoured?

The following is an example of what I would like to do:

    +------------------+---------------------------------------------------+
    | myFunction()     | .. deprecated:: 0.35                              |
    |                  |    Please use thisOtherFunction() instead.        |
    |                  |                                                   |
    |                  | A function which solves all your problems.        |
    +------------------+---------------------------------------------------+

**Comment by bbinet** [comment]
+1
